### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by SCharlesM** [SCharlesM/CLI-task-tracker#2]
To-do list to keep track of project progress and next steps

https://roadmap.sh/projects/task-tracker

- [x] write all functions
- [x] re-write 'Add' function with JSON 
- [x] write 'main' function for CLI input
- [x] 'finish' basic functionality
- [x] branch a development branch

**Comment by SCharlesM** [comment]
completed all tasks in this issue, so now closed
